# Uncomment this line to define a global platform for your project
platform :tvos, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DartsConnect' do
    pod 'CocoaAsyncSocket', '~> 7.4.2'
    pod 'CocoaSecurity', '~> 1.2.4'
    pod 'Bond'
    #pod 'Firebase'
end

target 'DartsConnectTests' do

end

target 'DartsConnectUITests' do

end